version: '3.8'
services:
  gitea: 
    build: 
      context: .
      dockerfile: docker/gitea.dockerfile
    container_name: devops_gitea
    ports:
      - '3000:3000'
      - '1212:22'
    environment:
      - USER=git
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - db 

  db:
    image: mysql:8-oracle
    restart: always
    container_name: devops_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql


  jenkins: 
    container_name: devops_jenkins
    build: 
      context: .
      dockerfile: docker/jenkins.dockerfile
    privileged: true
    user: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
